version: "3.3"

services:
  userservice:
    build:
      context: .
      args:
        - BIN_FOLDER=api
    image: userservice:latest
    environment:
      - MONGO_HOST=mongodb+srv://****
      - MONGO_DATABASE=****
      - MONGO_USERS_COLLECTION=users
      - JWT_SECRET=****
      - LISTEN_PORT=7755
      - LISTEN_HOST=userservice
      - EVENTS_URL=
    ports:
      - "7755:7755"
    develop:
      watch:
        - action: rebuild
          files:
            - ./**/*.go
            - ./go.mod
            - ./go.sum
